### ISSUE TITLE
Scorev2 scores are buggy in osu! Royale matches

### ISSUE THREAD

**Issue by Zyfarok** [Hughp135/osustuff-tournaments#20]
See round1 here : https://play.osustuff.org/lobbies/5f0dd802a67f776072371757
![image](https://user-images.githubusercontent.com/10669609/87944620-ec392400-ca9f-11ea-875e-19227a9d643a.png)
Yeah I know that was unfair but I also fced HDDT during the timer so I guess it's ok 👀...

so first thing : should Score v2 scores even be considered ? Now that v2 scores are submitted you could make the matches as using v2 since it's a more "balanced" scoring system, but if you want to keep score v1, then you should just ignore score v2 scores.

Second thing, the mod displayed are wrong. I played in HDDT+Scorev2 yet it displayed : "CN, RD, FI, PF, AP, SO, AU, FL, NC, HT, RX, HR, HD, TD, EZ, NF" (ScoreV2 binary value is 536870912 or 2^29, maybe you had some kind of overflow ?)

**Comment by hughp-abq** [comment]
oh i see, yes v2 scores submitting now would break the system.

**Comment by Hughp135** [comment]
I see, thank you for reporting.

The mods being displayed wrong is an easy fix, just gotta add the v2 mod to the enum.

It is unfair to compare V2 scores with V1 scores. I would like to move everything over to V2, but might need to gather some more feedback first.

**Comment by Hughp135** [comment]
I have fixed the display of v2 scores, but also disabled score v2 submissions for the time being, until it is decided whether we will use v2 or not.

**Comment by Hughp135** [comment]
Closing this for now as the poll in the discord came up that a significant percentage didn't want Score V2
