### ISSUE TITLE
Entering a lobby infinitely hangs

### ISSUE THREAD

**Issue by jvyden420** [Hughp135/osustuff-tournaments#8]
Creating lobbies works perfectly fine, however I have not been able to even *view* a lobby.

**Comment by Hughp135** [comment]
Do you get any errors in the console or network tab or backend logs?

**Comment by jvyden420** [comment]
No, I didn't notice any obvious errors. Nothing shows up in the console.

**Comment by Hughp135** [comment]
well, I didn't get the same issue on a fresh installation, so it seems there's some setup issues going on. This usually means that the socket connection is not established, as it is awaiting a response from the server.

**Comment by jvyden420** [comment]
How can I verify that the socket connection is established? All the other features seem to work fine.

**Comment by jvyden420** [comment]
Solved over Discord.
The problem was that the front-end config was not setup correctly. If you have this issue,
change `socket_url` in `front-end/src/environments/environment.ts` to match your server. An example can be found in the `environment.prod.ts` file.
